### ISSUE TITLE
phased bam input

### ISSUE THREAD

**Issue by pdimens** [pontushojer/NAIBR#6]
Is it possible to create the phased bam input without the use of longranger? My current workflow uses haplotagging and is not longranger compatible. I have unphased BWA alignments with BX tags that I would have as input.

**Comment by pontushojer** [comment]
It should be possible to run on a unphased BAM as long as you have the BX tag. I would however not be as sensitive and would probably only capture homozygous calls, look at the original article for details. 

However you might consider to assigning haplotypes to the unphased BAM using a phased VCF. [WhatsHap](https://whatshap.readthedocs.io/en/latest/) has a subcommand `haplotag` for this. Then output would be pretty similar to LongRanger.

**Comment by pdimens** [comment]
Ah awesome, thanks for explaining that. I'll try it out.
